name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest    
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: dotnet build
  
  test:
    name: Test
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Run tests
      run: dotnet test --no-build Test.LightweightIocContainer
    
